PLIB_SRC = Timers i2c CCP
USBHID_STDIO = true
PLIB_SOURCES = Timers CCP i2c EEP
INCLUDE_SOURCES = systick cmdline TSL2561 swSpiWrite hd44780 \
	smbus ds18x20 ds18x20_ex onewire crc8 assert

-include ../Makefile.redirect
